name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: configure directory   
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 2112
        script: |
          mkdir -p /var/www/html

    - name: Deploy to VPS
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 2112
        source: "./*"
        target: /var/www/html

    - name: configure database 
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 2112
        script: |
          cd /var/www/html
          git pull origin main
          docker-compose up -d --build
          docker exec keuangan-db mysql -u user -p123 -h127.0.0.1 -e "use keuangan; insert into data(id, keterangan, jenis) values (01,'kas rutin','pengeluaran');" keuangan
